apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogo-preproduction
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shigedangao/gogo
    targetRevision: HEAD
    chart: gogo
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: preproduction